### ISSUE TITLE
Make it more obvious what inputs are required

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hcs-governance#12]
Currently you need a discussion & description link to publish a proposal. This isn't obvious. We should fix that. 

In the short term, I think we can make these fields / inputs optional.

**Comment by bugbytesinc** [comment]
How about changing the text field hints to:

- Description (optional https/ipfs link or brief text)
- Discussion (optional https/ipfs link or brief text)

I understand this to mean the only required fields are **Title** and **Voting Period** then (since choices are currently hard-coded).

I would suggest the UI generate "n/a" when we have empty description & discussion fields so that we don't have to modify the server-side logic that treats these fields as required.  It would also reduce the chance of users thinking there was a bug in the platform if these fields were empty.

**Comment by Cooper-Kunz** [comment]
I am onboard with that. Let's do it.
