### ISSUE TITLE
Add quorum & circulating supply features

### ISSUE THREAD

**Issue by Cooper-Kunz** [the-creators-galaxy/hcs-governance#34]
## Details 
Currently the voting system just requires a simple majority. 

It would be valuable if within the `.env` configuration you could define the following variables: 

- CIRCULATING_SUPPLY_API
- MIN_VOTING_THRESHOLD

## Example usage

We could deploy the [hts-circulating-supply-api](https://github.com/the-creators-galaxy/hts-circulating-supply-api) somewhere, and add it's location to the environment configuration. Then, we could say that unless 10%  (a value of 0.1 in the `.env` config) of the circulating supply is used for a vote, then the vote cannot be considered as "passed" or successful - ensuring a minimum participation within a specific DAO or community. If the circulating_supply_API is not defined, it's assumed that the current number of tokens on the network (even the treasury account) are part of circulation. Similarly, if the MIN_VOTING_THRESHOLD is undefined, a simple majority of 51% should be used. If a vote fails to pass because of the quorum threshold not being met, that user would be able to resubmit the proposal for a subsequent vote after they have believed to accumulated more than 10% of the circulating supply's weight. 

## Other things to note

If / when this is decided upon, we should update [CGIP-4](https://github.com/the-creators-galaxy/creators-galaxy-improvement-proposals/blob/master/CGIP/cgip-4.md) to reflect this new quorum functionality.

---

Would love your thoughts @bugbytesinc

**Comment by bugbytesinc** [comment]
Some thoughts:

MIN_VOTING_THRESHOLD should default to 0 if not specified.  It will need to be explicitly echoed in the proposal definition and included in the checksum files as these values could change over time.

The tool itself should compute the circulating supply at the voting timestamp, it should also not rely on a third party app.  This feature will need to be directly embedded in all tools.  Instead of CIRCULATING_SUPPLY_API I suggest INELEGIBLE_WALLETS to be a comma separated list of treasury accounts.  This information will also need to be echoed in a proposal's definition as this type of information can change over time, as well as included in the file format creating checksum for verifying tool results.

**Comment by Cooper-Kunz** [comment]
Those suggestions make sense.

Can you elaborate on what impact this will have? 

> This information will also need to be echoed in a proposal's definition as this type of information can change over time, as well as included in the file format creating checksum for verifying tool results.

**Comment by bugbytesinc** [comment]
.env files are deployment specific, meaning any instance of the tool can set its own rules, if we don't echo the rules of the vote in the proposal definition, this will ultimately lead to confusion -- we can still reject proposals that do not adhere to the rules we wish to honor, but it is important to know what they were when the proposal was created.  

The "cheksum file" is just a deterministic representation of the ballot and votes so that different tools can compute the same checksum result, If a vote tally is using different rules, we need to ensure the results have a different checksum.
